### ISSUE TITLE
Fixed errors not removed from issues list

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#127]
I've been seeing an issue lately where there's an error, I fix it, but the error doesn't go away from the problems list. The only work around I've had to far is to restart VS Code. At least in some cases, there are still legit other errors, so maybe that's somehow preventing the fixed ones from getting removed?

I'm using VS Code, Windows 10, Soar Language Support 0.9.9

**Comment by adeschamps** [comment]
Is this reproduceable? Is this a project with multiple entry points? Could it be related to #71 by any chance?

**Comment by marinier** [comment]
Yes, this is for a project with multiple entry points. It could be related to #71, although the errors that I'm fixing should be fixed across all the agents (they share some files). If it were #71, then I wouldn't necessarily expect the problem to go away when I restart VS Code.

I have not yet reliably reproduced it (it seems to happen randomly), but I also haven't tried very hard to reproduce it. But I'll be working in this code again soon, so I'll see if I can figure out how to reproduce it.

**Comment by marinier** [comment]
I continue to see this and similar issues (e.g., tcl expansion not updating). I've tried to reproduce consistently, but it appears to be fairly random. I wonder if there's somehow a race condition between typing and the backend updating, where sometimes the latest typing isn't getting processed. I don't understand how this could be given how it works, but maybe there's an edge case we haven't accounted for?

The other strange aspect of it that doesn't really support the above explanation is that once it doesn't update correctly, it continues to not update correctly. E.g., making another change doesn't then fix it, which you'd expect if it was just a race condition (at least sometimes). But restarting VS Code does fix it. This implies that something is getting into a bad state.

I do often see this exception:
```
[ERROR] [2019-09-06 10:42:15,982] [pool-1-thread-1] [c.s.s.SoarDocumentService] Retrieving result of analysis
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.soartech.soarls.SoarDocumentService.getAnalysis(SoarDocumentService.java:170)
	at com.soartech.soarls.SoarDocumentService.lambda$getAnalysis$4(SoarDocumentService.java:157)
	at java.util.Optional.map(Optional.java:215)
	at com.soartech.soarls.SoarDocumentService.getAnalysis(SoarDocumentService.java:157)
	at com.soartech.soarls.SoarDocumentService.mapAnalysis(SoarDocumentService.java:958)
	at com.soartech.soarls.SoarDocumentService.hover(SoarDocumentService.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at com.soartech.soarls.SoarDocumentService.reportDiagnostics(SoarDocumentService.java:855)
	at com.soartech.soarls.SoarDocumentService.lambda$scheduleAnalysis$82(SoarDocumentService.java:844)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 common frames omitted
```

But IIRC we are using exceptions for control flow processing in some cases (even though we shouldn't be), so I can't tell if this is an exception that actually indicates a real problem or not.

**Comment by marinier** [comment]
Possibly related, it appears that at least sometimes when there is an error in the code (e.g., VS Code has underlined a rule), the ~tcl-expansion.soar file appears to "blink" every few seconds, even if I'm not typing anything or even touching the keyboard. Maybe it's repeatedly regenerating the tcl expansion for some reason, and this is preventing it from processing new updates?

**Comment by adeschamps** [comment]
That stack trace looks like it might be enough for me to track this down when I have a bit of time.

We generally don't use exceptions for control flow. There are a few cases in the analysis where we catch exceptions thrown by JSoar and report them as errors, but I don't believe those can make it out of that analysis.

This is a case where the analysis either returned `null` or was never started. I could put a null check around the line where the exception was thrown, but that's not the root cause - the intention of the design was that an analysis should never fail.

If this is blocking you from being productive, then we can still put a null check in as a temporary stop-gap while I track down the actual cause. Let me know if it's urgent to you.

**Comment by marinier** [comment]
I don't think it's super urgent (I don't need it today or next week), but it would be nice to have it in the next few weeks. Currently, if I spend a day writing Soar code, this causes issues at least 1-2 times a day (where time is lost because I'm trying to fix something that ultimately isn't a problem and I really just need to restart VS Code). Restarting VS Code is something I do a lot now, just to make sure problems are really problems. Luckily, it's very fast to restart.

**Comment by rjonessoar** [comment]
This is happening to me several times a day.  As Bob says, it's not really urgent. But it happens pretty frequently, and the only solution seems to be to save everything, quit, and restart VS Code.

**Comment by adeschamps** [comment]
Do folks find that this issue crops up when they're creating new files? If so, then I think #164 is the same issue.

**Comment by marinier** [comment]
It's definitely possible. I was certainly creating new files when I originally reported this issue, and I haven't been recently, and haven't seen the issue in a while (although I've generally been doing less Soar work recently).

**Comment by marinier** [comment]
Today I added a new file and 30 mins later I was having the problem again (in this case, the tcl expansion was still showing the old expansion -- I wasn't having issues with errors/warnings).
