### ISSUE TITLE
NullPointerException in SignatureHelp, possibly due to creating a new file in VSCode

### ISSUE THREAD

**Issue by sirnuke** [soartech/soar-language-server#164]
While working on my personal Discord agent, I'm seeing the following exception:

```
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:683)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at com.soartech.soarls.SoarDocumentService.lambda$mapAnalysis$89(SoarDocumentService.java:959)
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.soartech.soarls.SoarDocumentService.mapAnalysis(SoarDocumentService.java:959)
	at com.soartech.soarls.SoarDocumentService.signatureHelp(SoarDocumentService.java:756)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	(snip)
Caused by: java.lang.NullPointerException
	at com.soartech.soarls.SoarDocumentService.lambda$signatureHelp$75(SoarDocumentService.java:759)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	... 23 more
```

Seems JVM isn't reporting the full stack trace for where the exception actually occurred, but hopefully that's enough.  This seems to be caused by creating a new Soar source file.  VSCode, restarting seems to fix it.

Also have you heard the Good Word of Kotlin?

**Comment by adeschamps** [comment]
Thank you for this; it might be the root cause of #127, which I've been trying to track down.

I'll have to give some thought to how to handle this. Below are some details that you probably don't need to worry about, but I want to get this down because I don't think I'll get to this today:

---

Since we have to re-analyse the codebase on every edit, which can take a number of seconds, we made the decision that it's often okay to give slightly outdated information. The way this is implemented is that we store `analyses` (a `Map<URI, ProjectAnalysis>` of completed analyses) as well as `pendingAnalyses` (a `Map<URI, CompletableFuture<ProjectAnalysis>>` where the analysis might still be running in a background thread). When we need to respond to most queries, we usually call the `getAnalysis` method, which tries to return the pending analysis if it's ready, or else falls back on the most recently completed analysis if the pending analysis is still running. In most cases, you'll get the same results. In some cases, you'll get hover information that's offset by a few characters or something like that, which is unfortunate, but it's the tradeoff we made in order to have things be responsive.

I believe the issue is that when you make an edit (and the `didChange` notification is sent) we check whether the modified file is reachable from the agent's entry point in order to decide whether to schedule a new analysis. _However_, this function reads the `analyses` map directly instead of going through `getAnalysis`, so it will (almost by definition) receive outdated information, and when you create a new file, then it _doesn't_ appear in the last analysis. We _can't_ wait for the current analysis to complete though, because `didChange` needs to return quickly so it doesn't block the client. So basically, the server is saying "Does this change affect any of the code I'm analysing? No? Then there's no need to re-analyse the project." Somehow we need to bootstrap the analyses.

**Comment by adeschamps** [comment]
I'm going to keep this open until I do a release tomorrow and get a report that this is fixed.

**Comment by adeschamps** [comment]
Version 0.9.12 is in the CI pipeline. Once you've updated, could you let me know if this issue is fixed for you? Thanks!

**Comment by sirnuke** [comment]
No dice unfortunately.  Triple checked that I was on 0.9.12.

```
[Error - 1:21:09 AM] Request textDocument/signatureHelp failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:683)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at com.soartech.soarls.SoarDocumentService.lambda$mapAnalysis$89(SoarDocumentService.java:979)
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.soartech.soarls.SoarDocumentService.mapAnalysis(SoarDocumentService.java:979)
	at com.soartech.soarls.SoarDocumentService.signatureHelp(SoarDocumentService.java:776)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at com.soartech.soarls.SoarDocumentService.lambda$signatureHelp$75(SoarDocumentService.java:779)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	... 23 more
```
